language: go
go:
  - '1.9.x'
  - '1.10.x'
  - '1.11.x'
  # - master

sudo: false

before_install:
  - cd $HOME/gopath/src
  - git clone --depth=1 https://github.com/tomoncle/golang.org.git -b 1.11.5

install:
  - go get github.com/tomoncle/linux_service_exporter

script:
  - cd $HOME/gopath/src/github.com/tomoncle/linux_service_exporter
  - go run linux_service_exporter.go --version
  - go version
